import { vi } from "vitest";
import type { RustCoreExports } from "./rustTypes";

export function makeRustCoreExports(overrides: Partial<RustCoreExports> = {}): RustCoreExports {
  return {
    configureMemo: vi.fn(),
    configureNodeBudget: vi.fn(),
    getSolveStatus: vi.fn(() => 0),
    solveMinEf: vi.fn(),
    solveCore: vi.fn(() => 7),
    resAction: vi.fn(() => 2),
    resSuccessProb: vi.fn(() => 0.8),
    resMaxSuccessProb: vi.fn(() => 0.82),
    resVecB: vi.fn(() => 11),
    resVecP: vi.fn(() => 22),
    resVecY: vi.fn(() => 33),
    rootCandidateValid: vi.fn((action: number) => (action === 1 ? 0 : 1)),
    rootCandidateMaxSuccessProb: vi.fn(() => 0.9),
    rootCandidateSuccessProb: vi.fn((action: number) => (action === 0 ? 0.9 : 0.895)),
    rootCandidateVecB: vi.fn((action: number) => 10 + action),
    rootCandidateVecP: vi.fn((action: number) => 20 + action),
    rootCandidateVecY: vi.fn((action: number) => 30 + action),
    rootCandidateCost: vi.fn((action: number) => 0.1 + action),
    policyActionAt: vi.fn(() => 1),
    simulateCore: vi.fn(),
    simulateAfterFirstActionCore: vi.fn(),
    getMcCompleted: vi.fn(() => 80),
    getMcRuns: vi.fn(() => 100),
    getMcVecB: vi.fn(() => 1),
    getMcVecP: vi.fn(() => 2),
    getMcVecY: vi.fn(() => 3),
    statesCount: vi.fn(() => 1234),
    minEfAction: vi.fn(() => 0),
    minEfSuccessProb: vi.fn(() => 0.9),
    minEfMaxSuccessProb: vi.fn(() => 0.95),
    minEfVecB: vi.fn(() => 10),
    minEfVecP: vi.fn(() => 20),
    minEfVecY: vi.fn(() => 30),
    minEfExpectedCost: vi.fn(() => 0.123),
    minEfRootCandidateValid: vi.fn((action: number) => (action === 1 ? 0 : 1)),
    minEfRootCandidateMaxSuccessProb: vi.fn(() => 0.95),
    minEfRootCandidateSuccessProb: vi.fn((action: number) => (action === 0 ? 0.95 : 0.94)),
    minEfRootCandidateVecB: vi.fn((action: number) => 10 + action),
    minEfRootCandidateVecP: vi.fn((action: number) => 20 + action),
    minEfRootCandidateVecY: vi.fn((action: number) => 30 + action),
    minEfRootCandidateExpectedCost: vi.fn((action: number) => 0.1 + action),
    minEfActionAtOrSolve: vi.fn(() => 1),
    simulateExpectedFAfterFirstAction: vi.fn(),
    simulateExpectedFAfterFirstActionFromPolicy: vi.fn(),
    simulateExpectedFPairFromPolicy: vi.fn(),
    getMcEf: vi.fn(() => 0.456),
    getMcEfSumSq: vi.fn(() => 20.8),
    getMcEfRuns: vi.fn(() => 100),
    getMcEfCompletion: vi.fn(() => 0.99),
    getPairMeanBaseline: vi.fn(() => 0.2),
    getPairMeanSelected: vi.fn(() => 0.1),
    getPairMeanDelta: vi.fn(() => -0.1),
    getPairDeltaSumSq: vi.fn(() => 2),
    getPairRuns: vi.fn(() => 100),
    getPairCorrelation: vi.fn(() => 0.5),
    momentVectorAfterFirstActionFromPolicy: vi.fn(),
    momentMeanBUses: vi.fn(() => 1),
    momentMeanPUses: vi.fn(() => 2),
    momentMeanYUses: vi.fn(() => 3),
    momentSecondBBUses: vi.fn(() => 2),
    momentSecondPPUses: vi.fn(() => 6),
    momentSecondYYUses: vi.fn(() => 12),
    momentSecondBPUses: vi.fn(() => 3),
    momentSecondBYUses: vi.fn(() => 4),
    momentSecondPYUses: vi.fn(() => 8),
    momentVectorNodeCount: vi.fn(() => 42),
    cvarSetup: vi.fn(),
    cvarFollowMeanAfterFirstAction: vi.fn(() => 0.321),
    cvarNodeCount: vi.fn(() => 24),
    ...overrides,
  };
}
