import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  assertCertifiedWasmBuild,
  certifiedWasmBuildInputs,
} from "./certified-wasm-build-inputs.ts";

const root = new URL("../", import.meta.url);
if (!process.argv.includes("--rebuild")) {
  const artifact = assertCertifiedWasmBuild(root);
  console.log(`Pinned certified WASM ${artifact.bytes} bytes; sha256 ${artifact.hash}`);
  process.exit(0);
}
// Explicit source rebuild only. Machine-dependent build strings mean these
// bytes are not promised to reproduce across OSes; ship this pinned artifact.
const inputs = certifiedWasmBuildInputs(root);
const crate = fileURLToPath(new URL("../rust/certified/", import.meta.url));
const result = spawnSync(
  "cargo",
  ["build", "--offline", "--locked", "--release", "--target", "wasm32-unknown-unknown"],
  {
    cwd: crate,
    stdio: "inherit",
  },
);
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
const source = new URL(
  "../rust/certified/target/wasm32-unknown-unknown/release/certified_wasm.wasm",
  import.meta.url,
);
const bytes = readFileSync(source);
const hash = createHash("sha256").update(bytes).digest("hex");
if (certifiedWasmBuildInputs(root).hash !== inputs.hash)
  throw new Error("certified_wasm_source_changed_during_build");
copyFileSync(source, new URL("../public/certified_solver.wasm", import.meta.url));
writeFileSync(
  new URL("../shared/generated/certifiedWasmBuild.ts", import.meta.url),
  `// Generated by scripts/build-certified-wasm.ts.\nexport const CERTIFIED_WASM_HASH = "${hash}";\nexport const CERTIFIED_WASM_SOURCE_HASH = "${inputs.hash}";\n`,
);
console.log(`Certified WASM ${bytes.length} bytes; sha256 ${hash}`);
