import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import type { Plugin } from "vite";
import {
  assertCertifiedForecastAuthority,
  writeCertifiedForecastAuthority,
} from "./certified-forecast-authority.ts";
import { assertPinnedCertifiedForecastFiles } from "./certified-forecast-pins.ts";
import { assertCertifiedWasmBuild } from "./certified-wasm-build-inputs.ts";

const projectRoot = new URL("../", import.meta.url);
const fixtureManifests = [
  "forecast-collector/fixtures/official-solo-history/manifest.json",
  "forecast-collector/fixtures/pr-notice-evidence/manifest.json",
];
type EngineBuild = {
  codeHash: string;
  seedProvenanceHash: string;
  sources: { path: string; sha256: string }[];
  output: string;
};
export async function deriveCertifiedEngineBuild(root = projectRoot): Promise<EngineBuild> {
  assertCertifiedForecastAuthority(root);
  const graph = await build({
    absWorkingDir: fileURLToPath(root),
    entryPoints: [
      "src/certifiedRuntime/browserWorker.ts",
      "src/certifiedRuntime/nodeWorker.ts",
      "src/certifiedRuntime/browserClient.ts",
      "src/certifiedRuntime/nodeClient.ts",
      "src/lib/certifiedForecast.ts",
    ],
    bundle: true,
    write: false,
    metafile: true,
    outdir: ".certified-fingerprint-unused",
    format: "esm",
    platform: "neutral",
    packages: "external",
    external: ["node:*"],
    logLevel: "silent",
  });
  if (!graph.metafile) throw new Error("certified_engine_build_graph_missing");
  const paths = new Set(
    Object.keys(graph.metafile.inputs).filter(
      (path) => path !== "shared/generated/certifiedEngineBuild.ts",
    ),
  );
  const provenancePaths = new Set<string>();
  if (paths.has("shared/generated/certifiedWasmBuild.ts")) {
    const { inputs } = assertCertifiedWasmBuild(root);
    paths.add("public/certified_solver.wasm");
    for (const source of inputs.sources) paths.add(source.path);
  }
  // The runtime projection omits unused legacy profiles, while the trust anchor
  // includes the entire original registry, including every omitted profile.
  paths.add("shared/supplyForecasts.json");
  paths.add("shared/generated/certifiedForecastAuthority.ts");
  provenancePaths.add("shared/supplyForecasts.json");
  for (const manifest of fixtureManifests) {
    paths.add(manifest);
    provenancePaths.add(manifest);
    const pins = assertPinnedCertifiedForecastFiles(fileURLToPath(new URL(manifest, root)));
    for (const pin of pins) {
      const path = `${manifest.slice(0, -"manifest.json".length)}${pin.path}`;
      paths.add(path);
      provenancePaths.add(path);
    }
  }
  const sources = [...paths].sort().map((path) => ({
    path,
    sha256: createHash("sha256")
      .update(readFileSync(new URL(path, root)))
      .digest("hex"),
  }));
  return {
    codeHash: createHash("sha256").update(JSON.stringify(sources)).digest("hex"),
    seedProvenanceHash: createHash("sha256")
      .update(JSON.stringify(sources.filter((source) => provenancePaths.has(source.path))))
      .digest("hex"),
    sources,
    output: fileURLToPath(new URL("shared/generated/certifiedEngineBuild.ts", root)),
  };
}
function generatedContents(result: EngineBuild): string {
  return `// Generated by scripts/certified-engine-build.ts; checked before product builds.\nexport const CERTIFIED_ENGINE_CODE_HASH = "${result.codeHash}";\nexport const CERTIFIED_FORECAST_SEED_PROVENANCE_HASH = "${result.seedProvenanceHash}";\n`;
}
export async function assertCertifiedEngineBuild(root = projectRoot): Promise<EngineBuild> {
  const result = await deriveCertifiedEngineBuild(root);
  if (readFileSync(result.output, "utf8") !== generatedContents(result))
    throw new Error(
      "certified_engine_build_hash_stale: run npm run generate:certified-engine-build",
    );
  return result;
}
export async function writeCertifiedEngineBuild(root = projectRoot): Promise<EngineBuild> {
  writeCertifiedForecastAuthority(root);
  const result = await deriveCertifiedEngineBuild(root);
  writeFileSync(result.output, generatedContents(result));
  return result;
}
/** Direct Vite builds enforce the same guard as the package/CI commands. */
export function certifiedEngineBuildGuardPlugin(root = projectRoot): Plugin {
  return {
    name: "certified-engine-build-freshness",
    apply: "build",
    enforce: "pre",
    async buildStart() {
      await assertCertifiedEngineBuild(root);
    },
  };
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  console.log(
    JSON.stringify(
      await (process.argv.includes("--check")
        ? assertCertifiedEngineBuild()
        : writeCertifiedEngineBuild()),
    ),
  );
